export const companyProfile = {
  legalName: "Fieldhouse Forge Equipment Company",
  tradeName: "Fieldhouse Forge",
  companyType: "Fictional privately held manufacturer",
  founded: 1978,
  headquarters: "214 Foundry Way, Hickory, Indiana 47300",
  phone: "(888) 555-0142",
  email: "projects@fieldhouseforge.example",
  facility: "142,000 sq ft fictional fabrication and assembly facility",
  employees: "Approximately 185 fictional employees",
  serviceTerritory: [
    "Indiana",
    "Illinois",
    "Ohio",
    "Michigan",
    "Kentucky",
    "Wisconsin",
    "Nationwide through fictional qualified dealers",
  ],
  markets: [
    "K-12 education",
    "Higher education",
    "Municipal recreation",
    "Parks and public athletic complexes",
    "Community and nonprofit facilities",
  ],
  capabilities: [
    "Project-specific gymnasium equipment",
    "Strength and conditioning room planning",
    "Retractable and fixed seating coordination",
    "Wall padding and athletic surfaces",
    "Scoreboard and control coordination",
    "Outdoor field equipment",
    "Submittal drawings and product data",
    "Dealer-based delivery and installation coordination",
  ],
  classificationCodes: [
    { system: "NAICS", code: "339920", label: "Sporting and Athletic Goods Manufacturing" },
    { system: "UNSPSC", code: "49221500", label: "Sporting goods and equipment" },
    { system: "CSI", code: "11 66 23", label: "Gymnasium Equipment" },
    { system: "CSI", code: "11 66 53", label: "Gymnasium and Exercise Equipment" },
    { system: "CSI", code: "11 68 33", label: "Athletic Field Equipment" },
  ],
  procurement: [
    "Direct project quotation through an authorized fictional dealer",
    "Public bid and specification response",
    "Fictional cooperative contract FF-2026-14 for demo purposes only",
  ],
} as const;

